# Generated by Django 5.0.6 on 2024-07-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_feedback_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
