# Generated by Django 5.0.6 on 2024-06-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'process'), (2, 'confirmed'), (3, 'cancel')]),
        ),
    ]
