# Generated by Django 5.0.6 on 2024-06-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('process', 'process'), ('confirmed', 'confirmed'), ('cancel', 'cancel')], max_length=9),
        ),
    ]
